# Generated by Django 4.2.16 on 2024-11-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_set',
            field=models.BooleanField(default=False),
        ),
    ]
