# Generated by Django 4.2.16 on 2024-12-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='xp_reward',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
