# Generated by Django 4.2.16 on 2024-11-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blocked_user_name',
            field=models.CharField(blank=True, default='none', max_length=150),
        ),
    ]
