# Generated by Django 4.2.17 on 2024-12-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_new_requests',
        ),
    ]
