# Generated by Django 4.2.16 on 2024-10-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
