# Generated by Django 4.2.17 on 2024-12-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/defaultAvatar.jpeg', upload_to='avatars/'),
        ),
    ]
