# Generated by Django 4.2.16 on 2024-11-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.CharField(blank=True, default='Never', max_length=50),
        ),
    ]
