# Generated by Django 4.2.17 on 2024-12-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_oauth_user',
        ),
        migrations.AddField(
            model_name='user',
            name='oauth2_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='oauth2_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
