# Generated by Django 4.2.17 on 2024-12-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_has_new_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_chat',
            field=models.BooleanField(default=False),
        ),
    ]
