# Generated by Django 4.2.16 on 2024-11-25 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
