# Generated by Django 4.2.16 on 2024-12-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_password_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_password_set',
            field=models.BooleanField(default=True),
        ),
    ]
