# Generated by Django 4.2.16 on 2024-11-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='score_player1',
            new_name='loser_score',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='score_player2',
            new_name='winner_score',
        ),
    ]
