# Generated by Django 4.2.17 on 2024-12-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='name_trans',
            field=models.CharField(default='', max_length=255),
        ),
    ]
