# Generated by Django 4.2.16 on 2024-11-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_badge_alter_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.badge'),
        ),
    ]
