# Generated by Django 4.2.17 on 2024-12-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_oauth_user_user_oauth2_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_oauth2_user',
            field=models.BooleanField(default=False),
        ),
    ]
