# Generated by Django 4.2.16 on 2024-12-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_badge_xp_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='played_games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
