# Generated by Django 4.2.17 on 2024-12-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_achievement_name_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/DEFAULT.jpeg', upload_to='avatars/'),
        ),
    ]
