# Generated by Django 4.2.16 on 2024-12-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification_new_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_new_requests',
            field=models.BooleanField(default=False),
        ),
    ]
