# Generated by Django 4.2.16 on 2024-11-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.CharField(blank=True, default='Never', max_length=50),
        ),
    ]
