# Generated by Django 4.2.17 on 2024-12-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='state',
            field=models.TextField(default=''),
        ),
    ]
