# Generated by Django 4.2.16 on 2024-11-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_conversation',
            field=models.IntegerField(default=-1),
        ),
    ]
