# Generated by Django 4.2.14 on 2024-10-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_age_alter_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_oauth_user',
            field=models.BooleanField(default=False),
        ),
    ]
