# Generated by Django 4.2.14 on 2024-10-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_oauth2user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oauth2User',
        ),
    ]
