# Generated by Django 4.2.16 on 2024-10-30 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_blockrelationship_user_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_users', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BlockRelationship',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', through='accounts.BlockedUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
