# Generated by Django 4.2.16 on 2024-10-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='defaultAvatar.svg', upload_to='media/avatars/'),
        ),
    ]
