# Generated by Django 4.2.16 on 2024-10-30 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_blockrelationship_delete_blockeduser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
        migrations.AlterField(
            model_name='blockrelationship',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blockrelationship',
            name='date_blocked',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
