# Generated by Django 4.2.17 on 2025-01-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_options_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'base_manager_name': 'active'},
        ),
    ]
