# Generated by Django 4.2.16 on 2024-10-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_avatar'),
        ('accounts', '0010_remove_user_is_blocked_and_more'),
    ]

    operations = [
    ]
