# Generated by Django 4.2.16 on 2024-11-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='unread_messages',
            new_name='unread_messages_user1',
        ),
        migrations.AddField(
            model_name='conversation',
            name='unread_messages_user2',
            field=models.IntegerField(default=0),
        ),
    ]
