# Generated by Django 4.2.16 on 2024-11-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_unread_messages_conversation_unread_messages_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message',
            field=models.TextField(blank=True, default='Send first message', null=True),
        ),
    ]
