# Generated by Django 4.2.17 on 2024-12-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='p1_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='p2_xp',
            field=models.IntegerField(default=0),
        ),
    ]
