# Generated by Django 4.2.16 on 2024-11-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('started', 'Game started'), ('ended', 'Game ended')], default='started', max_length=20),
        ),
    ]
