# Generated by Django 4.2.16 on 2024-11-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='max_players',
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('started', 'Game started'), ('ended', 'Game ended')], default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_players',
            field=models.IntegerField(default=8),
        ),
    ]
