# Generated by Django 4.2.16 on 2024-10-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_address',
        ),
    ]
