# Generated by Django 4.2.17 on 2024-12-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0002_game_p1_xp_game_p2_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players_connected',
            field=models.BooleanField(default=False),
        ),
    ]
