# Generated by Django 4.2.16 on 2024-11-22 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchmaker', '0002_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('started', 'Game started'), ('ended', 'Game ended')], default='started', max_length=20),
        ),
        migrations.CreateModel(
            name='MultiGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('p1_score', models.IntegerField(default=0)),
                ('p2_score', models.IntegerField(default=0)),
                ('p3_score', models.IntegerField(default=0)),
                ('p4_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('started', 'Game started'), ('ended', 'Game ended')], default='started', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_games_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_games_as_player2', to=settings.AUTH_USER_MODEL)),
                ('player3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_games_as_player3', to=settings.AUTH_USER_MODEL)),
                ('player4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_games_as_player4', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_games_as_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
