# Generated by Django 4.2.16 on 2024-11-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0002_remove_tournament_max_players_alter_game_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
