# Generated by Django 4.2.16 on 2024-11-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0003_tournament_is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_players',
            field=models.IntegerField(default=4),
        ),
    ]
