# Generated by Django 4.2.17 on 2024-12-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0005_alter_game_players_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='multigame',
            name='players_connected',
            field=models.BooleanField(default=False),
        ),
    ]
