# Generated by Django 4.2.17 on 2024-12-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0006_multigame_players_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='players_connected',
            field=models.BooleanField(default=False),
        ),
    ]
