# name: Checks

# on: [push]

# jobs:
#   test-lint:
#     name: Test and Lint
#     # runs-on: ubuntu-20.04
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up Docker
#         uses: docker/setup-buildx-action@v2 # Sets up Docker Buildx
#         with:
#           install: true # Ensure Docker is installed

#       - name: Install Docker Compose
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y docker-compose

#       # - name: Run docker-compose
#       #   uses: hoverkraft-tech/compose-action@v2.0.1
#       #   with:
#       #     compose-file: "./docker/docker-compose.yml"

#       - name: Check Docker Compose version
#         run: docker-compose --version

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2 # Ensure this is the latest version
#         with:
#           username: ${{ secrets.DOCKERHUB_USER }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Checkout
#         uses: actions/checkout@v4 # Latest version, v3 should be good

#       - name: Test
#         run: docker-compose run --rm backend sh -c "python manage.py wait_for_db && python manage.py test"

#       # - name: Lint
#       #   run: docker-compose run --rm backend sh -c "flake8"


name: No-Op Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  no_op_job:
    runs-on: ubuntu-latest

    steps:
      - name: No operation
        run: echo "No actions performed."
